/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Topbar from './Topbar/topbar'
import Navbar from './Navbar/navbar'
import Banner from './Banner/Bannner'
import About from './About/About'

import Signup from './Signup/Signup'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="https://kit.fontawesome.com/d7b789e221.js" />
          
      </Head>
      <Topbar></Topbar>
      <Navbar></Navbar>
      <Banner></Banner>
      <About></About>
      <Signup></Signup>


    </div>

  )
}
